# Generated by Django 5.2.3 on 2025-06-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("domain", models.CharField(blank=True, max_length=100)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=255
                    ),
                ),
                (
                    "prizeAmount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "nonMonetaryRewards",
                    models.TextField(
                        blank=True, help_text="Describe any non-monetary rewards."
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("benefits", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        default="Medium",
                        max_length=10,
                    ),
                ),
                ("website", models.URLField(blank=True, max_length=255)),
                ("organizer", models.CharField(blank=True, max_length=150)),
                ("timeCommitment", models.CharField(blank=True, max_length=100)),
                (
                    "teamRequirement",
                    models.CharField(
                        choices=[
                            ("Individual", "Individual"),
                            ("Team", "Team"),
                            ("Both", "Both"),
                        ],
                        default="Both",
                        max_length=20,
                    ),
                ),
                ("targetAudience", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "competition_details",
            },
        ),
    ]
